### ISSUE TITLE
How can i change the const value PROP_K in matlab?

### ISSUE THREAD

**Issue by liushuai00** [jlizier/jidt#52]
I wanna change the k property, but how?

**Comment by jlizier** [comment]
Hi,

I presume you mean the property value assigned to the property labelled by PROP_K, rather than wishing to change the value of the const PROP_K.

Please see Matlab/Octave example 4 [https://github.com/jlizier/jidt/wiki/OctaveMatlabExamples#example-4---transfer-entropy-on-continuous-data-using-kraskov-estimators](https://github.com/jlizier/jidt/wiki/OctaveMatlabExamples#example-4---transfer-entropy-on-continuous-data-using-kraskov-estimators) -- i.e. `teCalc.setProperty('k', '4');`

By the way, the "Issues" section is for bug reports only. If you have a general support issue, please contact us via our google groups mailing list (see the home page)

**Comment by liushuai00** [comment]
That's it. Really appreciate your email. Wish you good luck.

在2016-03-11 17:40:58，刘帅liushuai00@buaa.edu.cn写道：

Hi,

I presume you mean the property value assigned to the property labelled by PROP_K, rather than wishing to change the value of the const PROP_K.

Please see Matlab/Octave example 4 https://github.com/jlizier/jidt/wiki/OctaveMatlabExamples#example-4---transfer-entropy-on-continuous-data-using-kraskov-estimators -- i.e. teCalc.setProperty('k', '4');

By the way, the "Issues" section is for bug reports only. If you have a general support issue, please contact us via our google groups mailing list (see the home page)
