### ISSUE TITLE
Typo at "step kernel" description?

### ISSUE THREAD

**Issue by IAmLFish** [jlizier/jidt#54]
@jlizier 
In your thesis at **2.2.3 Information-theoretic measures of continuous variables** and also in **Schreiber's Paper "Measuring information transfer"**, both of you indicate `Theta(x > 0) = 1` and `Theta(x <= 0) = 0` for the step kernel.
Currently, I think **it should be the other way around**, i.e. `Theta(x > 0) = 0` and `Theta(x <= 0) = 1` because even your implementation (KernelEstimatorMultiVariate.java, line 958) expresses my understanding of the kernel definition:
```java
public int stepKernel(double[] observation, double[] candidate) {
	for (int d = 0; d < dimensions; d++) {
		if (Math.abs(observation[d] - candidate[d]) > kernelWidthsInUse[d]) {
			return 0;
		}
	}
	// The candidate is within epsilon of the observation
	return 1;
}
```
Can you confirm this?

**Comment by jlizier** [comment]
Thanks @IAmLFish -- you are right that the thesis and Schreiber have the incorrect maths here, and that the implementation in the JIDT code has it the correct way. In fact, I've noticed that before and fixed it in the [JIDT paper](https://arxiv.org/abs/1408.3270) (see Appendix B.2.b) as well as in our [recent book on transfer entropy](http://dx.doi.org/10.1007/978-3-319-43222-9) (section 3.4.1.4, which writes the equations in a slightly different form).
So I'll close this issue since there is no problem with the code.
