### ISSUE TITLE
Multivariate estimator for groups of columns?

### ISSUE THREAD

**Issue by dizcza** [jlizier/jidt#74]
I find your project interesting but I don't see the support for multivariate distributions. For example, I'd like to compute the mutual information between two high-dimensional vectors X and Y and check the results with what I'm currently using - https://github.com/gregversteeg/NPEET. But your JIDT seems to capture only one dimension at a time. Do you plan adding Kraskov estimator to capture multicolumn computations?

**Comment by jlizier** [comment]
Hi @dizcza - support for multivariate distributions is there for most measures / estimators combinations, it's just a little less obvious because they're not implemented in our AutoAnalyser GUI at this point. For some measures/estimators there are separate classes for these (e.g. for the Kraskov TE calculators), for others it is handled in the one class with overloaded addObservations() methods (e.g. on the Kraskov MI calculator). In general, you can use them in a similar fashion as the univariate classes, just passing 2D arrays into addObservations() (where the first dimension is time or sample index, and the second dimension is variable index). Please see an example doing MI with the Kraskov estimator on multivariates on [this wiki page](https://github.com/jlizier/jidt/wiki/SimpleJavaExamples#example-6---late-binding-mutual-info-calculator) -- ignore all the parts there about late binding, just check out how the multivariate calculate in it differs from the univariate one which is done first (there's very little difference).

Also -- you mentioned that you're looking at doing this for high dimensional vectors, so for that I would also recommend checking whether your results are statistically significant (since you're likely pushing the statistical power here). See the JIDT paper regarding that.

In future - if you have a question, it's more appropriate to post it to our google groups list or email it to me rather than raise it as an issue here, since a question is not a bug (issues are really for bug reports).
