### ISSUE TITLE
Kraskov calculators to ensure they use actual k in joint space than assumed k

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jlizier/jidt#8]
```
At the moment, our Kraskov calculators assume that they have k values within 
epsilon in the full joint space. Where the distribution is composed of delta 
functions (i.e. somewhat discretised) this won't be the case - there could be 
many more than k. As such, it may be more correct to use the actual k for each 
observation in contributing digamma(k) - 1/k, then averaging, rather than 
assume the parameter k.
This may add significantly to the runtime however so we could either:
- just issue a warning were this to occur, or
- track the actual k values in an array, then compute digamma(k) - 1/k once for 
each distinct value and add these in to the result.
```

Original issue reported on code.google.com by `joseph.lizier` on 7 Sep 2012 at 5:47

**Comment by jlizier** [comment]
With the inclusion of adding noise to the values by default, we can safely assume that we won't be getting these <= cases anymore for the main KSG estimators. This may still effect the Conditional MI mixed discrete-continuous KSG calculator, which is the only one which does not add noise to the (continuous) data yet. That needs to be fixed regardless, I've opened issue #63 to work on that specifically, rather than continuing under the more general title here.
