### ISSUE TITLE
Error when enabling GPU support on Ubuntu LTS 18.04

### ISSUE THREAD

**Issue by martinfrasch** [jlizier/jidt#80]
CUDA is installed, I double-checked.

Executing ant gpu from JIDT dir I get this error:
[exec] Makefile:99: recipe for target '../bin/cuda/kraskovCuda.o' failed
     [exec] kraskovCuda.c:1:10: fatal error: jni.h: No such file or directory
     [exec]  #include <jni.h>
     [exec]           ^~~~~~~
     [exec] compilation terminated.
     [exec] make: *** [../bin/cuda/kraskovCuda.o] Error 1
Any suggestions?
Thank you!

**Comment by martinfrasch** [comment]
PS. I updated Java SDK to current detault which is 11. I then re-ran and got this error:
 [exec] Makefile:105: recipe for target '../bin/cuda/libKraskov.so' failed
     [exec] nvcc fatal   : Unknown option 'Wl,-O2'
     [exec] make: *** [../bin/cuda/libKraskov.so] Error 1

**Comment by pmediano** [comment]
Hi Martin,

That's unexpected -- for a start, there's no `-O2` flag in the Makefile, so not sure where that's coming from. I have a couple of questions and a suggestion:

0) I'm guessing the answer to this is yes, but have you tried compiling from source and running other CUDA projects? Both the CUDA runtime and its compiler, NVCC, can be annoying and it's good to double-check you can compile and run other code.

1) Could you check that you have all the relevant object files in `bin/cuda/`? You should have `digamma.o gpuMILibrary.o gpuCMILibrary.o kraskovCuda.o libgpuKnnLibrary.a`.

2) If all the object files mentioned above are there, could you try compiling `libKraskov.so` manually? It should be something like this:

`nvcc -O3 -D_FORCE_INLINES -Xcompiler -Wall -I. -I./cub -I${JNI_INCLUDE} -I${JNI_INCLUDE}/linux -Xcompiler -fPIC -shared -o ../bin/cuda/libKraskov.so ../bin/cuda/digamma.o ../bin/cuda/gpuMILibrary.o ../bin/cuda/gpuCMILibrary.o ../bin/cuda/kraskovCuda.o -L. -L../bin/cuda -lcuda -lcudart -lgpuKnnLibrary`

Where `${JNI_INCLUDE}` should be replaced with the location of your `jni.h` file (in my Arch machine, that's in `/usr/lib/jvm/default/include`), and the command should be run from the `cuda/` folder.

Hope this helps! Please let me know if the errors persist.

**Comment by martinfrasch** [comment]
Hi Pedro and thank you so much for the quick reply!!!

0. The primary goal of my GPU is for deep learning and it works for that.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

I wonder if the issue arises due to the older version which is what we get
when running an LTS release.

1. I do not have kraskovCuda.o and I cannot locate it anywhere. Perhaps
adding this is all we need to solve this issue? If so, would you be able to
please send this file?

2. Once received, I will test as per your instructions in 2.

Thank you very much again!

With best regards,
martin

**Comment by pmediano** [comment]
Hi Martin,

`kraskovCuda.o` is one of the intermediate files produced during compilation, so we need to have it compiled in your machine (it's very likely that just sending mine over won't work).

This file in particular (`kraskovCuda.o`) is the one that depends on `jni.h`, and the one that failed in your first message in this issue. To rule out that this missing file is a consequence of that problem, I'd recommend first running `make clean all` to delete all the intermediate files and compile from scratch again.

If that doesn't work, then you can try to compile `kraskovCuda.o` manually as follows:

`g++ -I. -I./cub -I${JNI_INCLUDE} -I${JNI_INCLUDE}/linux -O3 -Wall -Wextra -Wno-unused-parameter -x c -std=c99 -fPIC -c kraskovCuda.c -o ../bin/cuda/kraskovCuda.o`

**Comment by martinfrasch** [comment]
Hi Pedro,

Thank you!

0.

I ran everything inside the /bin directory, otherwise, I get the error that

g++: error: kraskovCuda.c: No such file or directory

1.

*make clean all* generated a great number of error messages.

2.

Manual compilation as you advised produced the following error:

kraskovCuda.c:1:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.

I looked up that I may need to add the path for the compiler to find jni.h
as explained here:
https://stackoverflow.com/questions/14529720/how-to-make-jni-h-be-found

So I amended this to


*g++ -I. -I./cub -I${JNI_INCLUDE} -I${JNI_INCLUDE}/linux -O3 -Wall -Wextra
-Wno-unused-parameter -x c -std=c99 -fPIC -c kraskovCuda.c -o
../bin/cuda/kraskovCuda.o -I/usr/lib/jvm/java-11-openjdk-amd64/include \
-I/usr/lib/jvm/java-11-openjdk-amd64/include/linux*

and got this error:

g++: error:  : No such file or directory

A disclaimer: I have no experience with compilers at this level of
proficiency, so I may be doing something wrong and stupid without knowing
it.

This is where I am at. Thank you for your patient help as I am trying to
get that CUDA to work with the program!

Best regards,
Martin

**Comment by pmediano** [comment]
Hi Martin,

0. What happens when you run these commands inside the `bin/` folder? They should be run in the same folder where the `Makefile` and `kraskovCuda.c` are, which (unless you've moved things around) is the `jidt/cuda/` folder (see e.g. https://github.com/jlizier/jidt/tree/master/cuda ).

1. What is that great number of error messages? I'd still suggest we try to make the Makefile work, as that will make our life simpler. If you could try again running `make clean all` from `jidt/cuda/` and send me any error messages that might come out.

2. You seem to have successfully found your JNI folder. I apologise if my previous suggestion wasn't clear -- I meant you should replace `${JNI_INCLUDE}` with the right folder (in your case, `/usr/lib/jvm/java-11-openjdk-amd64/include`). So try running this:

`g++ -I. -I./cub -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux -O3 -Wall -Wextra -Wno-unused-parameter -x c -std=c99 -fPIC -c kraskovCuda.c -o ../bin/cuda/kraskovCuda.o`

I suspect the `error:  : No such file or directory` is happening because your terminal is expanding `${JNI_INCLUDE}` as an empty string (just try to run `echo ${JNI_INCLUDE}` and you should see an empty line), and then `g++` can't find any folder with an empty name.

I hope this helps! If problems persist, please send me a line to my personal email (which you can find in any of my recent papers, e.g. [this](https://arxiv.org/abs/2004.08220)) and we can take it from there.

Cheers,
P

**Comment by pmediano** [comment]
Issue was caused by a conflicting previous value of the LDFLAGS variable. Makefile has been edited with a more specific name to avoid this problem in the future.
