### ISSUE TITLE
Non-deterministic behaviour in Octave JIDT interface for Int matrices

### ISSUE THREAD

**Issue by pmediano** [jlizier/jidt#85]
Here's a minimally working example in Octave/Matlab (assuming the JIDT jar and `demos/octave` have been added to the path):

```octave
z = [0 0 1 1; 0 1 2 3]';
miCalc = javaObject('infodynamics.measures.discrete.MutualInformationCalculatorDiscrete', 2, 4, 0);
miCalc.initialise();
mean(miCalc.computeLocal(octaveToJavaIntMatrix(z), 0, 1))
```

When run in Matlab, this code returns the correct value of 1 bit, but when run in Octave it often (though not always) gives a wrong result. This is (as far as I can tell) because of an ambiguous overloading of `loadIntData(int[], int[])` and `loadIntData(boolean[], int[])` in `utils/OctaveMatrix.java`. When the `int[]` version is used everything goes well, but when the `boolean[]` version is used the input is misinterpreted as `[0 0 1 1; 0 1 1 1]` and the (incorrect) result is ~0.31128 bit.

I suspect this error may happen with `octaveToJavaIntArray` too, but I haven't tested it.

As a potential solution, I suggest disambiguating the two overloads by renaming one to `loadBooleanData(boolean[], int[])` and using `islogical()` in `octaveToJavaIntMatrix.m` to call one or the other.

**Comment by jlizier** [comment]
Thanks Pedro for identifying this - but I have a feeling I already fixed it in [this commit](https://github.com/jlizier/jidt/commit/17bf0e0be73a7aef88dfda0a2ff0f714e7f2c6e1#diff-a69947e9458f7d4a8d97bfaff4cd87298cfee0d19c77aec1c2bdd7ce44e3215b) and you're looking at some older code, since:
1. the current version of `utils/OctaveMatrix.java` does not have an overload `loadIntData(boolean[], int[])`  (there's only a method signature for `loadIntData(int[], int[])`) -- that was changed to `loadBooleanAsIntData` in that commit, and
2. `octaveToJavaIntMatrix.m` and `octaveToJavaIntMatrix.m` were altered to detect and utilise the non-overloaded signature in that commit (in a slightly different way to what you suggest).

Could you check that it all works after updating to the current version of the repo?

**Comment by pmediano** [comment]
Well, this is embarrassing -- it works well with the latest version of the code. My bad! Thanks for pointing this out [:

**Comment by jlizier** [comment]
No probs Pedro -- would rather false alarms than not find out about a potential problem :)
