### ISSUE TITLE
Source history length parameter in Transfer Entropy using Kernel estimator

### ISSUE THREAD

**Issue by Bharathi-A-7** [jlizier/jidt#90]
The kernel estimator for Transfer Entropy does not seem to have any option to define the source history length paramter 'l'. Is it set to a default value of 1? I am only able to tune the destination history length 'k'. What about problems where past values of Y apart from yn affect Xn+1? 

Is the source length set to 1 by default or am I missing something? I would like to tune the source parameter as well when computing transfer entropy using kernel estimation.

Could someone help me with this?

**Comment by jlizier** [comment]
Yes, the embedding parameters beyond target history length are not implemented for the kernel estimator, and it is unlikely that they will be. This is because the kernel estimator is superseded by the KSG estimator, and it is only implemented and included here for comparison purposes (e.g. to Schreiber's early TE demos). I suggest you move to the KSG estimator if you want to set these.

For the kernel estimator yes the source embedding length is set to 1.
