### ISSUE TITLE
Why is the transfer entropy of the same variable 0 bits on kernel?

### ISSUE THREAD

**Issue by airampg** [jlizier/jidt#97]
Hi all, 

I am wondering why, when I calculate the TE of the same column as the source and the destination, the result is 0.0 bits. 
I thought the correlation should be maximum, and expected the information transfer to be able to completely predict X based on the value of X, but that is clearly not the case. 

I have tried with random data as well as time series data, with the same result. 

![image](https://github.com/jlizier/jidt/assets/41060873/2e403d19-c329-4c47-a9e4-258090a2a712)

To reproduce: 
1) Transfer Entropy mode. 
2) Calculator type to kernel
3) Select. e.g. 2coupledRandomCols-1.txt
4) You should see what I see on the image above. 

Thank you!

**Comment by jlizier** [comment]
Not a bug. The transfer entropy of any variable to itself *must* be 0, because you the past of a variable cannot add new information about it's future, given it's own past. I.e. the source is the same as the conditional variable in the conditional MI here. You're thinking more of a lagged mutual information (that does not condition on the variable's past) than the transfer entropy (which does).
Might be useful for you to review the video lectures on transfer entropy in our [YouTube course](https://github.com/jlizier/jidt/wiki/Course) -- the videos on TE start from number 33.

**Comment by airampg** [comment]
Thank you for your kind answer, Professor. I will have a look at the videos you link to aid my understanding. Have a nice day!
